/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	char str[32];
	int choice;
	SystemInit();
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	UartInit(9600);
	while(1){
	do
	{
		UartPuts("Enter your choice\r\n");
		UartPuts("1. Red Led On\r\n");
		UartPuts("2. Red Led Off\r\n");
		UartPuts("3. Blue Led On\r\n");
		UartPuts("4. Blue Led Off\r\n");
		UartGets(str);
		sscanf(str,"%d",&choice);
		switch(choice)
		{
			case 1:
					UartPuts("Red led on\r\n");
					LedOn(LED_RED_PIN);
					break;

			case 2:
					UartPuts("Red led off\r\n");
					LedOff(LED_RED_PIN);
					break;

			case 3:
					UartPuts("Red led on\r\n");
					LedOn(LED_BLUE_PIN);
					break;

			case 4:
					UartPuts("Red led off\r\n");
					LedOff(LED_BLUE_PIN);
					break;
			default:
					UartPuts("Invalid choice\r\n");
		}
	}while(choice==0);

	}
/*while(1) {
		LedBlink(LED_RED_PIN, 100);
		LedBlink(LED_BLUE_PIN, 100);
		UartGets(str);
		strupr(str);
		UartPuts(str);
	}
	char str[32];
int choice;
UartGets(str);
sscanf(str, "%d", &choice);
switch(choice) {
// ...
} */
	return 0;
}





